cmake_minimum_required(VERSION 3.15)
project(GrannyTacticalLab LANGUAGES C CXX ASM)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_subdirectory(${SHADOWHOOK_SOURCE}/shadowhook/src/main/cpp shadowhook)
target_compile_options(shadowhook PRIVATE -Wno-error -Wno-everything)
target_link_options(shadowhook PRIVATE -Wl,--undefined-version)
add_library(granny_csgo SHARED native/main.cpp)
target_include_directories(granny_csgo PRIVATE native ${GENERATED_SOURCE} ${SHADOWHOOK_SOURCE}/shadowhook/src/main/cpp/include)
target_link_libraries(granny_csgo PRIVATE shadowhook android log dl)
target_compile_options(granny_csgo PRIVATE -Wall -Wextra -Werror=return-type -fvisibility=hidden)
target_link_options(granny_csgo PRIVATE -Wl,-z,max-page-size=16384)
